SELECT states.STATE_NAME AS STATE,
       MAX(people.QUIZ_POINTS) AS MAXPOINTS,
       AVG(people.QUIZ_POINTS) AS AVGPOINTS
FROM states
JOIN people ON states.STATE_ABBREV = people.STATE_CODE
GROUP BY states.STATE_NAME
ORDER BY AVGPOINTS DESC;